/*
 * generated by Xtext 2.17.0
 */
package org.xtext.sdu.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractIoTScopeProvider extends DelegatingScopeProvider {
}
