/**
 * generated by Xtext 2.17.0
 */
package org.xtext.sdu.ioT;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Server</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.sdu.ioT.Server#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.sdu.ioT.Server#getLip <em>Lip</em>}</li>
 *   <li>{@link org.xtext.sdu.ioT.Server#getSip <em>Sip</em>}</li>
 *   <li>{@link org.xtext.sdu.ioT.Server#getGroup <em>Group</em>}</li>
 * </ul>
 *
 * @see org.xtext.sdu.ioT.IoTPackage#getServer()
 * @model
 * @generated
 */
public interface Server extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.sdu.ioT.IoTPackage#getServer_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.sdu.ioT.Server#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Lip</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Lip</em>' containment reference.
   * @see #setLip(Portnumber)
   * @see org.xtext.sdu.ioT.IoTPackage#getServer_Lip()
   * @model containment="true"
   * @generated
   */
  Portnumber getLip();

  /**
   * Sets the value of the '{@link org.xtext.sdu.ioT.Server#getLip <em>Lip</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Lip</em>' containment reference.
   * @see #getLip()
   * @generated
   */
  void setLip(Portnumber value);

  /**
   * Returns the value of the '<em><b>Sip</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sip</em>' containment reference.
   * @see #setSip(Portnumber)
   * @see org.xtext.sdu.ioT.IoTPackage#getServer_Sip()
   * @model containment="true"
   * @generated
   */
  Portnumber getSip();

  /**
   * Sets the value of the '{@link org.xtext.sdu.ioT.Server#getSip <em>Sip</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sip</em>' containment reference.
   * @see #getSip()
   * @generated
   */
  void setSip(Portnumber value);

  /**
   * Returns the value of the '<em><b>Group</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Group</em>' reference.
   * @see #setGroup(DeviceGroup)
   * @see org.xtext.sdu.ioT.IoTPackage#getServer_Group()
   * @model
   * @generated
   */
  DeviceGroup getGroup();

  /**
   * Sets the value of the '{@link org.xtext.sdu.ioT.Server#getGroup <em>Group</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Group</em>' reference.
   * @see #getGroup()
   * @generated
   */
  void setGroup(DeviceGroup value);

} // Server
